version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - internal_network  # Internal-only network
    command: ["redis-server", "--bind", "0.0.0.0"]

  flask_app:
    build:
      context: .
    ports:
      - "44444:44444"
    networks:
      - internal_network
      - external_network
    depends_on:
      - redis
    entrypoint: ["./wait-for-redis.sh", "redis", "python", "netninja_server.py"]

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge  # This allows Flask to be accessible externally
