version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - internal_network
    command: ["redis-server", "--bind", "0.0.0.0"]

  flask_app:
    build:
      context: .
    ports:
      - "44444:44444"  # Map Flask app's port to external
    networks:
      - internal_network
      - external_network
    depends_on:
      - redis
    entrypoint: ["./wait-for-redis.sh", "redis", "gunicorn", "netninja_server:app", "--bind", "0.0.0.0:44444"]

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge
